version: '2'
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        links:
            - app
        volumes:
            - ./:/var/www
            - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        ports:
            - "3000:3000"
    mysql:
        image: mariadb
        environment:
            - "MYSQL_ROOT_PASSWORD=123456"
            - "MYSQL_DATABASE=laravel_app"
        ports:
            - "33061:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql
        ports:
            - 8183:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: 123456
            PMA_ARBITRARY: 1
    redis:
        image: redis
        ports:
            - "63791:6379"